DROP TABLE IF EXISTS pokemon_moves;
DROP TABLE IF EXISTS pokemon_abilities;
DROP TABLE IF EXISTS pokemon_types;
DROP TABLE IF EXISTS move;
DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    dex_number INTEGER,
    image_url TEXT NOT NULL,
    generation INTEGER NOT NULL
);

CREATE TABLE pokemon_abilities (
    pokemon_id INTEGER NOT NULL,
    ability_name TEXT NOT NULL,
    PRIMARY KEY (pokemon_id, ability_name),
    FOREIGN KEY (pokemon_id) REFERENCES pokemon(id)
);

CREATE TABLE pokemon_types (
    pokemon_id INTEGER NOT NULL,
    type_name TEXT NOT NULL,
    PRIMARY KEY (pokemon_id, type_name),
    FOREIGN KEY (pokemon_id) REFERENCES pokemon(id)
);

CREATE TABLE move (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- S'ha corregit la sintaxi
    name TEXT UNIQUE,
    type TEXT
);

CREATE TABLE pokemon_moves (
    pokemon_id INTEGER NOT NULL,
    move_id INTEGER NOT NULL,
    PRIMARY KEY (pokemon_id, move_id),
    FOREIGN KEY (pokemon_id) REFERENCES pokemon(id),
    FOREIGN KEY (move_id) REFERENCES move(id)
);
